apiVersion: apps/v1
kind: statefulset
metadata:
  name: mysql
  labels:
    app: myapp 
spec: 
  replicas: 3
  selector:
    matchlabels: 
      app: myapp
    template:
    metadata:
      name: mysql-template
      labels:
        app: myapp
      spec:
      containers: 
        - name: mysql-container
          image: mysql:8.0
          ports:
            - name: mysql-port
              containers: 3306
          env:
            - name: MSQL_USER
              valueFrom:
              configMapkeyRef:
                name: my-config
                key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
              configMapkeyRef:
                name: my-config
                key: mysql_password
            - name: MSQL_DATABASE
              valueFrom:
              configMapkeyRef:
                name: my-config
                key: msql_database
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
              configMapkeyRef:
                name: my-config
                key: mysql_root_password
... 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: mysql-svc
  labels: 
    app: myapp
  spec:
    clusterIP: None 
    selector: 
      app: myapp
      ports:
        - name: myport 
          protocol: TCP
          port: 3306
          targetPort: 3306
          