apiVersion: v1 
kind: ConfigMap
metadata:
  name: my-config
  labels:
    app: myapp
    data: 
    mysql_user: admin
    mysql_password: admin123
    mysql_root_password: root
    mysql-database: studentapp
