apiVersion: apps/v1 
kind: DaemonSet 
metadata: 
  name: my-daemon 
  labels: 
    app: myapp
spec: 
  selector: 
    matchLabels: 
      app: myapp 
  template: 
    metadata: 
      name: my-template 
      labels: 
        app: myapp 
    spec: 
      containers: 
        - name: daemoncontainer 
          image: amazon/cloudwatch-agent
          ports: 
            - name: daemonport 
              containerPort: 80