apiVersion: apps/v1
kind: DaemonSet
metadata:
  mane: my-daemon
  labels:
    app: myapp
spec: 
  selector:
     matchlabels:
       app: myapp
       template: 
         metadata:
            name: my-template
            labels:
              app: myapp
  spec:
   containerPort:
      - name: daemoncontainer
        image: amazon/cloudwatch-agent
        port: 
          - name: demonport
            containerPort: 80