apiVersion: v1 
kind: Pod 
metadata: 
  name: mypod 
  labels: 
    app: myapp
spec: 
  volumes: 
  - name: my-vol
    persistentVolumeClaim: 
      claimName: my-pvc
  containers: 
    - name: nginx-container
      image: nginx:latest 
      ports: 
      - name: myport 
        containerPort: 80 
      volumeMounts: 
        - name: my-vol
          mountPath: /usr/share/nginx/html/